[package]
name = "kcl-lib-jni"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
doc = false

[dependencies]
jni = "0.21.1"
anyhow = "1"
once_cell = "1.19.0"
lazy_static = "1.4.0"
kcl-lang = { git = "https://github.com/kcl-lang/lib", version = "0.7.5" }
